/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.*;
import Tools.Convert;
import Tools.ThongBao;
import bus.Khach_DoanBUS;
import bus.Nv_DoanBUS;
import java.util.logging.Level;
import java.util.logging.Logger;
import Tools.Rename;
import bus.DoanDuLichBUS;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class CHITIETDOAN extends javax.swing.JFrame {

    MAIN main = MAIN.main;

    /**
     * Creates new form JFrameThemtour
     */
    public CHITIETDOAN() {
        initComponents();
        Rename.khach();
        Rename.nhanvien();
        jTextFielddoan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableDskhach_doan = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jComboBoxkhach = new javax.swing.JComboBox();
        jTextFielddoan = new javax.swing.JTextField();
        jButtonthemkhachdoan = new javax.swing.JButton();
        jButtonsuakhachdoan = new javax.swing.JButton();
        jButtonxoakhachdoan = new javax.swing.JButton();
        NHIEMVU2 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableDsnhiemvu2 = new javax.swing.JTable();
        jPanelnv3 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldnhiemvu2 = new javax.swing.JTextField();
        jComboBoxnv2 = new javax.swing.JComboBox();
        jButtonthemnhiemvu = new javax.swing.JButton();
        jButtonsuanhiemvu = new javax.swing.JButton();
        jButtonxoanhiemvu = new javax.swing.JButton();
        jButtonxoanhiemvu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm Tour");
        setResizable(false);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Khách và Nhân Viên Theo Đoàn ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        //table = new JTable()
        //{
            //  public boolean isCellEditTable(int row, int column)
            //    {
                //        for (int i=0;i<table.getRowCount();i++)
                //        {
                    //            if(row==i)
                    //            {
                        //                return false;
                        //            }
                    //        }
                //        return true;
                //    }
            //};
        jTableDskhach_doan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Đoàn", "Khách"
            }
        ));
        jTableDskhach_doan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDskhach_doanMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableDskhach_doan);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đoàn - Khách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel38.setText("Đoàn:");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("Khách:");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxkhach, 0, 239, Short.MAX_VALUE)
                    .addComponent(jTextFielddoan)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxkhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButtonthemkhachdoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonthemkhachdoan.setText("THÊM");
        jButtonthemkhachdoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemkhachdoanActionPerformed(evt);
            }
        });

        jButtonsuakhachdoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonsuakhachdoan.setText("SỬA");
        jButtonsuakhachdoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuakhachdoanActionPerformed(evt);
            }
        });

        jButtonxoakhachdoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonxoakhachdoan.setText("XÓA");
        jButtonxoakhachdoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoakhachdoanActionPerformed(evt);
            }
        });

        NHIEMVU2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N
        NHIEMVU2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        //table = new JTable()
        //{
            //  public boolean isCellEditTable(int row, int column)
            //    {
                //        for (int i=0;i<table.getRowCount();i++)
                //        {
                    //            if(row==i)
                    //            {
                        //                return false;
                        //            }
                    //        }
                //        return true;
                //    }
            //};
        jTableDsnhiemvu2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Đoàn", "Nhân viên", "Nhiệm vụ"
            }
        ));
        jTableDsnhiemvu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDsnhiemvuMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jTableDsnhiemvu2);

        jPanelnv3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhiệm vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanelnv3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel48.setText("Nhân viên:");

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel49.setText("Nhiệm vụ:");

        jTextFieldnhiemvu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnhiemvujTextFieldnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelnv3Layout = new javax.swing.GroupLayout(jPanelnv3);
        jPanelnv3.setLayout(jPanelnv3Layout);
        jPanelnv3Layout.setHorizontalGroup(
            jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnv3Layout.createSequentialGroup()
                .addGroup(jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxnv2, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldnhiemvu2))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelnv3Layout.setVerticalGroup(
            jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnv3Layout.createSequentialGroup()
                .addGroup(jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxnv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelnv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnhiemvu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        jButtonthemnhiemvu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonthemnhiemvu.setText("THÊM");
        jButtonthemnhiemvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemnhiemvuActionPerformed(evt);
            }
        });

        jButtonsuanhiemvu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonsuanhiemvu.setText("SỬA");
        jButtonsuanhiemvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuanhiemvuActionPerformed(evt);
            }
        });

        jButtonxoanhiemvu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonxoanhiemvu.setText("XÓA");
        jButtonxoanhiemvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoanhiemvuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NHIEMVU2Layout = new javax.swing.GroupLayout(NHIEMVU2);
        NHIEMVU2.setLayout(NHIEMVU2Layout);
        NHIEMVU2Layout.setHorizontalGroup(
            NHIEMVU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelnv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(NHIEMVU2Layout.createSequentialGroup()
                .addComponent(jButtonthemnhiemvu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsuanhiemvu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonxoanhiemvu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NHIEMVU2Layout.setVerticalGroup(
            NHIEMVU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NHIEMVU2Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NHIEMVU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthemnhiemvu)
                    .addComponent(jButtonsuanhiemvu)
                    .addComponent(jButtonxoanhiemvu))
                .addContainerGap())
        );

        jButtonxoanhiemvu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonxoanhiemvu1.setText("QUAY LẠI");
        jButtonxoanhiemvu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoanhiemvu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButtonthemkhachdoan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsuakhachdoan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonxoakhachdoan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonxoanhiemvu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NHIEMVU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthemkhachdoan)
                    .addComponent(jButtonsuakhachdoan)
                    .addComponent(jButtonxoakhachdoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonxoanhiemvu1))
            .addComponent(NHIEMVU2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDskhach_doanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDskhach_doanMouseClicked
        // TODO add your handling code here:
        jTextFielddoan.setText((jTableDskhach_doan.getModel().getValueAt(jTableDskhach_doan.getSelectedRow(), 0)).toString());
        jComboBoxkhach.setSelectedItem((jTableDskhach_doan.getModel().getValueAt(jTableDskhach_doan.getSelectedRow(), 1)).toString());
    }//GEN-LAST:event_jTableDskhach_doanMouseClicked

   
    private void jButtonthemkhachdoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemkhachdoanActionPerformed
        // TODO add your handling code here:
        String ten = jTextFielddoan.getText();
        int madoan = Integer.valueOf(ten);
        int makhach = Rename.makhach[jComboBoxkhach.getSelectedIndex()];
        Khach_DoanBUS kdBUS = new Khach_DoanBUS();
        kdBUS.add(madoan, makhach);
        DoanDuLichBUS dBus = new DoanDuLichBUS();
        dBus.updateDoanhthu(madoan);
        try {
            
            ThongBao.noitice("Thêm thành công");
            kdBUS.updateTable(jTableDskhach_doan, madoan);
            jComboBoxkhach.setSelectedIndex(0);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonthemkhachdoanActionPerformed
 public static ArrayList<Integer> arrTenKhach; 
    private void jButtonsuakhachdoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuakhachdoanActionPerformed
        // TODO add your handling code here:
        String ten = jTextFielddoan.getText();
        int madoan = Integer.valueOf(ten);
        int makhach = Rename.makhach[jComboBoxkhach.getSelectedIndex()];
        int column = 1;
        int row = jTableDskhach_doan.getSelectedRow();
        int value = arrTenKhach.get(row);      
        Khach_DoanBUS kdBUS = new Khach_DoanBUS();
        kdBUS.edit(madoan, makhach,value);
        try {
            ThongBao.noitice("Sửa thành công");
            kdBUS.updateTable(jTableDskhach_doan, madoan);
            jComboBoxkhach.setSelectedIndex(0);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonsuakhachdoanActionPerformed

    private void jButtonxoakhachdoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoakhachdoanActionPerformed
//         TODO add your handling c ode here: int[] makhach;
        int mak = Rename.makhach[jComboBoxkhach.getSelectedIndex()];
        int madoan = Integer.valueOf(jTextFielddoan.getText());
        Khach_DoanBUS kdBUS = new Khach_DoanBUS();
        kdBUS.delete(mak, madoan);
        DoanDuLichBUS dBus = new DoanDuLichBUS();
        dBus.updateDoanhthu(madoan);
        try {
            ThongBao.noitice("Xóa thành công");
            String mapn = jTextFielddoan.getText();
            kdBUS.updateTable(jTableDskhach_doan, madoan);
            jComboBoxkhach.setSelectedIndex(0);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonxoakhachdoanActionPerformed

    private void jButtonxoanhiemvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoanhiemvuActionPerformed
        int makh = Rename.manv[jComboBoxnv2.getSelectedIndex()];
        int madoan = Integer.valueOf(jTextFielddoan.getText());
        Nv_DoanBUS nvBUS = new Nv_DoanBUS();
        nvBUS.delete(makh, madoan);
        try {
            ThongBao.noitice("Xóa thành công");
            String mapn = jTextFielddoan.getText();
            nvBUS.updateTable(jTableDsnhiemvu2, madoan);
            jComboBoxnv2.setSelectedIndex(0);
            jTextFieldnhiemvu2.setText(null);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonxoanhiemvuActionPerformed
public static ArrayList<Integer> arrTenNhanvien; 
    private void jButtonsuanhiemvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuanhiemvuActionPerformed
         String ten = jTextFielddoan.getText();
        int madoan = Integer.valueOf(ten);
        int makhach = Rename.manv[jComboBoxnv2.getSelectedIndex()];
        String nhiemvu= jTextFieldnhiemvu2.getText();
        int column = 1;
        int row = jTableDsnhiemvu2.getSelectedRow();
        int value = arrTenNhanvien.get(row);      
        Nv_DoanBUS nvBUS = new Nv_DoanBUS();
        nvBUS.edit(madoan, makhach,nhiemvu,value);
        try {
            ThongBao.noitice("Sửa thành công");
            nvBUS.updateTable(jTableDsnhiemvu2, madoan);
            jComboBoxnv2.setSelectedIndex(0);
            jTextFieldnhiemvu2.setText(null);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonsuanhiemvuActionPerformed

    private void jButtonthemnhiemvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemnhiemvuActionPerformed
        // TODO add your handling code here:
        String ten = jTextFielddoan.getText();
        int madoan = Integer.valueOf(ten);
        int makhach = Rename.manv[jComboBoxnv2.getSelectedIndex()];
        String nhiemvu = jTextFieldnhiemvu2.getText();
        Nv_DoanBUS nvBUS = new Nv_DoanBUS();
        nvBUS.add(madoan, makhach, nhiemvu);
        try {
            ThongBao.noitice("Thêm thành công");
            nvBUS.updateTable(jTableDsnhiemvu2, madoan);
            jTextFieldnhiemvu2.setText(null);
            jComboBoxnv2.setSelectedIndex(0);

        } catch (Exception ex) {
            Logger.getLogger(MAIN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonthemnhiemvuActionPerformed

    private void jTextFieldnhiemvujTextFieldnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnhiemvujTextFieldnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnhiemvujTextFieldnvActionPerformed

    private void jTableDsnhiemvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDsnhiemvuMouseClicked
        jTextFielddoan.setText((jTableDsnhiemvu2.getModel().getValueAt(jTableDsnhiemvu2.getSelectedRow(), 0)).toString());
        jComboBoxnv2.setSelectedItem((jTableDsnhiemvu2.getModel().getValueAt(jTableDsnhiemvu2.getSelectedRow(), 1)).toString());
        jTextFieldnhiemvu2.setText((jTableDsnhiemvu2.getModel().getValueAt(jTableDsnhiemvu2.getSelectedRow(), 2)).toString());
    }//GEN-LAST:event_jTableDsnhiemvuMouseClicked

    private void jButtonxoanhiemvu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoanhiemvu1ActionPerformed
        try {
            // TODO add your handling code here:
            main.setVisible(true);
            main.dBUS.updateTable(main.jTableDsdoan);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(CHITIETDOAN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonxoanhiemvu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHITIETDOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHITIETDOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHITIETDOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHITIETDOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHITIETDOAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NHIEMVU2;
    private javax.swing.JButton jButtonsuakhachdoan;
    private javax.swing.JButton jButtonsuanhiemvu;
    private javax.swing.JButton jButtonthemkhachdoan;
    private javax.swing.JButton jButtonthemnhiemvu;
    private javax.swing.JButton jButtonxoakhachdoan;
    private javax.swing.JButton jButtonxoanhiemvu;
    private javax.swing.JButton jButtonxoanhiemvu1;
    public static javax.swing.JComboBox jComboBoxkhach;
    public static javax.swing.JComboBox jComboBoxnv2;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelnv3;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JTable jTableDskhach_doan;
    public static javax.swing.JTable jTableDsnhiemvu2;
    public static javax.swing.JTextField jTextFielddoan;
    private javax.swing.JTextField jTextFieldnhiemvu2;
    // End of variables declaration//GEN-END:variables
}
